import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/app/component/Header";
import Footer from "@/app/component/Footer";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: {
        default:"Project of kitare",
        template:"Template %s"
    }
    ,
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <>
            <Header/>
            <div style={{height:'90px',background:"orange"}} />
            {children}
            <Footer/>
        </>


    );
}