

export const  GET_RESPONSE_CHAT_GPT="GET_RESPONSE_CHAT_GPT";
export const SAVE_CHAT_CONSERVATION = "SAVE_CHAT_CONSERVATION";
export const FETCH_FAKE_DATA = "FETCH_FAKE_DATA";


//CHAT SUPPORT ENGLISH ACTION
export const CHAT_CONSERVATION_ENGLISH = "CHAT_CONSERVATION_ENGLISH";


//BLOG ACTION
export const BLOG_CREATE="BLOG_CREATE"
export const BLOG_FIND_ONE="BLOG_FIND_ONE"
export const BLOG_ADD_CMT="BLOG_ADD_CMT"
export const BLOG_LIKE="BLOG_LIKE"
export const BLOG_UNLIKE="BLOG_UNLIKE"
export const BlOG_SHOW_ALL="BLOG_SHOW_ALL"
export const BlOG_REPORT="BlOG_REPORT"
export const BlOG_REPORT_COMMENT="BlOG_REPORT_COMMENT"
export const BlOG_REPLY_COMMENT="BlOG_REPLY_COMMENT"
export const BlOG_EDIT="BlOG_EDIT"
export const BlOG_REMOVE="BlOG_REMOVE"
export const BlOG_COMMENT_REMOVE="BlOG_COMMENT_REMOVE"

//TOPIC ACION
export const TOPIC_FIND_ALL="TOPIC_FIND_ALL"
export const TOPIC_FIND_ONE="TOPIC_FIND_ONE"

// LOGIN
export const LOGIN="LOGIN"

// REGISTER
export const REGISTER="REGISTER"

// LOGOUT
export const LOGOUT="LOGOUT"


//GROUP
export const GROUP_SHOW_ALL="GROUP_SHOW_ALL"
export const GROUP_SHOW_ONE="GROUP_SHOW_ONE"
export const GROUP_NOTIFICATION_SHOW_ALL="GROUP_NOTIFICATION_SHOW_ALL"
export const GROUP_CREATE_NOTIFICATION="GROUP_CREATE_NOTIFICATION"
export const GROUP_GET_ALL_MEMBER="GROUP_GET_ALL_MEMBER"
export const GROUP_REMOVE_MEMBER="GROUP_REMOVE_MEMBER"
export const GROUP_JOIN="GROUP_JOIN"
export const GROUP_FIND_BY_NAME="GROUP_FIND_BY_NAME"
export const GROUP_CREATE="GROUP_CREATE"
export const GROUP_CREATE_DOC="GROUP_CREATE_DOC"
export const GROUP_GET_DOC="GROUP_GET_DOC"

//SALE ACTION

export const SAlE_SHOW_ALL="GROUP_SHOW_ALL"


