import Navitem from "@/app/component/Navitem";
import type { Metadata } from "next";
import { Inter } from "next/font/google";


const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: {
        default:"Project of kitare",
        template:"Template %s"
    }
    ,
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    // @ts-ignore
    return (
        <>
         <div className="g-sidenav-show  bg-gray-100">
                <Navitem />
          
            {children}
            </div>
        </>


    );
}