import type { Metadata } from "next";
import { Inter } from "next/font/google";

import Header from "@/app/component/Header";
import Footer from "@/app/component/Footer";
import CarouselComponent from "@/app/component/Carousel";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: {
        default:"Project of kitare",
        template:"Template %s"
    }
    ,
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    // @ts-ignore
    return (
        <>
            <Header />
            <div style={{height:'120px',background:"orange"}} />
            {children}
          
            <Footer/>
        </>


    );
}