import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import {Providers} from "./store/provider";
import {ToastContainer} from "react-toastify";
import Header from "@/app/component/Header";
import Footer from "@/app/component/Footer";
import "../../public/css/style.css"
import "../../public/css/bootstrap.css"
import "../../public/lib/animate/animate.min.css"
import "../../public/lib/owlcarousel/assets/owl.carousel.min.css"


const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
    title: {
        default: "Project of kitare",
        template: "Template %s"
    }
    ,
    description: "Generated by create next app",
};

export default function RootLayout({
                                       children,
                                   }: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
        <body className={inter.className}>
        <Providers>
            {children}
        </Providers>
        <ToastContainer/>
        </body>
        </html>
    );
}
