
import type {Metadata} from "next";
import {Inter} from "next/font/google";
import "./globals.css";
import 'react-toastify/dist/ReactToastify.css';
import {Providers} from "./store/provider";
import {ToastContainer} from "react-toastify";

const inter = Inter({subsets: ["latin"]});

export const metadata: Metadata = {
  title: {
    default: "Project of kitare",
    template: "Template %s"
  }
  ,
  description: "Generated by create next app",
};

export default function RootLayout({
                                     children,
                                   }: Readonly<{
  children: React.ReactNode;
}>) {
  return (
      <html lang="en">
      <body className={inter.className}>
      <h1>Header</h1>
      <Providers>
        {children}
      </Providers>
      <h1>Footer</h1>
      <ToastContainer />

      </body>
      </html>
  );
}
